### ISSUE TITLE
cif_core: downgrade the dev version number to 2.5.0-dev-

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/DDL1-legacy-dictionaries#11]
The last officially released version of the DDL1 version of the `CIF_CORE` dictionary was 2.4.5. Since 2017 the dictionary underwent several maintenance updates each of which was assigned a version number with the dictionary finally arriving at the current version of 2.5.3. However, since these intermediate versions have never been officially released, and some of the maintenance updates involved partially undoing previous maintenance updates, I would like to roll all of the previous maintenance changes into a single 2.5.0-dev-... version and eventually properly release it as version 2.5.0.

A similar version squash should be carried out to other dictionaries that had more than one intermediate maintenance version.

**Comment by nautolycus** [comment]
This seems OK to me.

**Comment by vaitkus** [comment]
Resolved by merging PR #12.
