### ISSUE TITLE
ddl_core.dic: _enumeration_range does not allow upper bound values

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/DDL1-legacy-dictionaries#2]
This issue was first referenced by Marcin Wojdyr in the cif-developers mailing list: http://www.iucr.org/__data/iucr/lists/cif-developers/msg00314.html

The _enumeration_range data item is defined as having the following syntax:
``(_sequence_minimum):((_sequence_maximum)?)``

That is, both ``0:1`` and ``0:`` are accepted values, but the ``:1`` is not. However, both the DDL1 and DDLm versions of the cif_core.dic contain data item with only the upper range bound (DDL1: ``_diffrn_standards_decay_%``,  DDLm: ``_diffrn_standard.decay_percent``, ``_refine_diff.density_min``).

The DDLm dictionary definition does not make it clear if the values that have only the upper or the lower bound are valid ("_The inclusive range of values "from:to" allowed for the defined item._") so it could not be used as a reference in this case.

I propose updating the_ enumeration_range syntax to allow upper bound ranges:
``((_sequence_minimum):((_sequence_maximum)?))|(:(_sequence_maximum))``.
This approach has been implemented in the [upper-bound-range-values](https://github.com/COMCIFS/DDL1-legacy-dictionaries/tree/test/upper-bound-range-values) branch.

**Comment by jamesrhester** [comment]
I agree that this is a reasonable change.

**Comment by vaitkus** [comment]
The proposed change has been merged into the master branch.
