### ISSUE TITLE
ddl_core.dic: _dictionary_version data type incompatability

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/DDL1-legacy-dictionaries#3]
The ddl_core.dic defines the ``_dictionary_version`` data item as being of type ``numb``. However, in multiple dictionaries a versioning schema, similar to that described in http://semver.org/, is used. The schema in question uses three elements to describe the current version number in the form of ``<MAJOR>.<MINOR>.<PATCH>``, as a result, leaving the version number in conflict with the CIF1.1 numb format.

I propose the following possible solutions:
1) Introduce a 'version' data type and define it in a similar way that is done in the DDLm dictionary. The only data item that would have this data type would be ``_dictionary_version``. This, however, would probably break the software that relies on there only being 3 data types (``numb``, ``char``, ``null``);
2) Convert current dictionary versions values to numeric values. For example, version 1.0.5 could be converted to 1.0005 where the <MINOR> and the <PATCH> components would be assigned two digits. This, however, would probably break the software that relies on the current version format.
3) Change the data type from ``numb`` to ``char`` and add the ``_type_construct`` data item to the definition: ``(_major_version)[.](_minor_version)[.](_patch_version)``, where _major_version, _minor_version, _patch_version conforms to the requirements described in http://semver.org/ (non-negative integers that must not contain leading zeroes). This type of change seems to have the least chance of breaking anything. This approach has been implemented in the [version-numbers](https://github.com/COMCIFS/DDL1-legacy-dictionaries/tree/test/ddl-core/version-numbers) branch.

**Comment by jamesrhester** [comment]
I agree that option 3 is the best approach.

**Comment by vaitkus** [comment]
Option 3 has been merged into the master branch.
