### ISSUE TITLE
Rename the default branch from 'master' to 'main'

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/DDL1-legacy-dictionaries#6]
This potential reasons for renaming the branch are provide in issue https://github.com/COMCIFS/comcifs.github.io/issues/11.

This repository does not seem to be actively used so it is quite safe to rename the default branch. However, I do not have sufficient permissions to do so.

**Comment by jamesrhester** [comment]
Permissions updated and branch name changed.

**Comment by vaitkus** [comment]
Thanks!
